/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentVerifyRouteImport } from './routes/payment-verify'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentVerifyRoute = PaymentVerifyRouteImport.update({
  id: '/payment-verify',
  path: '/payment-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/payment-verify': typeof PaymentVerifyRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/payment-verify': typeof PaymentVerifyRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/payment-verify': typeof PaymentVerifyRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/login'
    | '/payment-verify'
    | '/register'
    | '/shop'
    | '/account'
    | '/checkout'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/shipping'
    | '/product/$slug'
    | '/admin/'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/payment-verify'
    | '/register'
    | '/shop'
    | '/account'
    | '/checkout'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/shipping'
    | '/product/$slug'
    | '/admin'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/login'
    | '/payment-verify'
    | '/register'
    | '/shop'
    | '/_authenticated/account'
    | '/_authenticated/checkout'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/shipping'
    | '/product/$slug'
    | '/admin/'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PaymentVerifyRoute: typeof PaymentVerifyRoute
  RegisterRoute: typeof RegisterRoute
  ShopRoute: typeof ShopRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-verify': {
      id: '/payment-verify'
      path: '/payment-verify'
      fullPath: '/payment-verify'
      preLoaderRoute: typeof PaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PaymentVerifyRoute: PaymentVerifyRoute,
  RegisterRoute: RegisterRoute,
  ShopRoute: ShopRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
