UPDATE public.products 
SET image_url = 'https://nefepnufdoskvnadvxfw.supabase.co/storage/v1/object/sign/product-images/nlt-africa-edition.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9jOWM0ZTRkMS04NTMzLTQzODktYWQ4Mi00MmQxNmFlOTE0ZGIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwcm9kdWN0LWltYWdlcy9ubHQtYWZyaWNhLWVkaXRpb24ucG5nIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4NzIyMzUyMiwiZXhwIjoyMTAyNTgzNTIyfQ.9Nbvc1cqjd0Qn78wX4hAOfRtcsaWWduJ_c_c-UScnFk'
WHERE name = 'NLT HARDCOVER AFRICA EDITION BIBLE';

UPDATE public.products 
SET image_url = 'https://nefepnufdoskvnadvxfw.supabase.co/storage/v1/object/sign/product-images/kjv-teal-mini-pocket.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9jOWM0ZTRkMS04NTMzLTQzODktYWQ4Mi00MmQxNmFlOTE0ZGIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwcm9kdWN0LWltYWdlcy9ranYtdGVhbC1taW5pLXBvY2tldC5wbmciLCJzY29wZSI6ImRvd25sb2FkIiwiaWF0IjoxNzg3MjIzNTIyLCJleHAiOjIxMDI1ODM1MjJ9.kgiTQo0zZekacyTeTyvyL0C7zqOTFPTBnV1oKcufVHw'
WHERE name = 'KJV TEAL FAUX LEATHER MINI POCKET BIBLE WITH ZIP';

UPDATE public.products 
SET image_url = 'https://nefepnufdoskvnadvxfw.supabase.co/storage/v1/object/sign/product-images/nlt-compact-burgundy.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9jOWM0ZTRkMS04NTMzLTQzODktYWQ4Mi00MmQxNmFlOTE0ZGIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwcm9kdWN0LWltYWdlcy9ubHQtY29tcGFjdC1idXJndW5keS5wbmciLCJzY29wZSI6ImRvd25sb2FkIiwiaWF0IjoxNzg3MjIzNTIyLCJleHAiOjIxMDI1ODM1MjJ9.9uxHhk_iPU87cXStO1pGDmIgjAKsZVUwLvhQCKdtyYo'
WHERE name = 'NLT COMPACT BIBLE BURGUNDY HARDCOVER';

UPDATE public.products 
SET image_url = 'https://nefepnufdoskvnadvxfw.supabase.co/storage/v1/object/sign/product-images/kjv-brown-lion-compact.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9jOWM0ZTRkMS04NTMzLTQzODktYWQ4Mi00MmQxNmFlOTE0ZGIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwcm9kdWN0LWltYWdlcy9ranYtYnJvd24tbGlvbi1jb21wYWN0LnBuZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODcyMjM1MjIsImV4cCI6MjEwMjU4MzUyMn0.5KsypAeyzzoS53hOweblHRnfW1HZOzBa5nsg6xqm3VM'
WHERE name = 'KJV BROWN LION FAUX LEATHER COMPACT BIBLE WITH ZIP';

UPDATE public.products 
SET image_url = 'https://nefepnufdoskvnadvxfw.supabase.co/storage/v1/object/sign/product-images/setswana-1970-black.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9jOWM0ZTRkMS04NTMzLTQzODktYWQ4Mi00MmQxNmFlOTE0ZGIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwcm9kdWN0LWltYWdlcy9zZXRzd2FuYS0xOTcwLWJsYWNrLnBuZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODcyMjM1MjIsImV4cCI6MjEwMjU4MzUyMn0.UtzP8k8DMpGnXnXO2VKVqj1sBagw3gt05j2tRUeMHEM'
WHERE name = 'SETSWANA 1970 BLACK HARDCOVER BIBLE MEDIUM';

UPDATE public.products 
SET image_url = 'https://nefepnufdoskvnadvxfw.supabase.co/storage/v1/object/sign/product-images/niv-green-forest.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9jOWM0ZTRkMS04NTMzLTQzODktYWQ4Mi00MmQxNmFlOTE0ZGIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwcm9kdWN0LWltYWdlcy9uaXYtZ3JlZW4tZm9yZXN0LnBuZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODcyMjM1MjIsImV4cCI6MjEwMjU4MzUyMn0.VGmmej1qmsat9pKonHrVsK2O3mkr_Ph3sTUCy7iRohI'
WHERE name = 'NIV HOLY BIBLE GREEN FOREST DESIGN FLEXCOVER';